# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: DCI 271 New Dark Age
email: brooksm@wlu.edu
description: >- # this means to ignore newlines until "baseurl:"
  Are we living in a "New Dark Age?” Artist and writer James Bridle argues that the abundance of information intended to enlighten the world has, in practice, darkened it. This course will take a big picture look at the interconnected impact of technology on the world around us. Is it enough to learn to code or think computationally? Are we simply at the mercy of unstable and inevitable technological progress? How can we think and act with justice and agency in a world where there is too much to know? How can we uncover the hidden material traces of technology in our surroundings? Through research, hands-on assignments, and local trips, we will seek to understand what has led to our present technological moment and where we can go from here. We will cover topics such as climate change, e-waste, big data, algorithmic bias, and automation. Our goal will be to create new metaphors for understanding the systems around us. 
baseurl: "/dci271-s20-newdarkage" # the subpath of your site, e.g. /blog
url: "https://mackenziekbrooks.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: 
github_username:  mackenziekbrooks
color_scheme: dark

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

prose:
  metadata:
    _posts:
      - name: tags
        field:
          element: visible
          label: tags
          value: deadtech
  rooturl: _posts
  ignore:
    - index.md
    - _config.yml
    - /_layouts
    - /_includes
    - assignments.md
    - schedule.md
    - course-info.md
    - /slides
  siteurl: "https://mackenziekbrooks.github.io/dci271-s20-newdarkage"
  media: assets/images


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.

#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
